spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/475798662/dond.git
#          search-paths:
#          username: 
#          password: 
server:
  port: 7001